#Data Source config
spring.datasource.url=jdbc:postgresql://localhost:5432/shoppingCart
spring.datasource.username=postgres
spring.datasource.password=root

#JPA config
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto= update

#JWT
jwt.secret = secret
jwt.expiration= 3600
jwt.accessTokenCookieName= AuthToken
